name: health_app_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^13.0.0
  flutter_native_splash: ^2.3.8
  intl: ^0.19.0
  google_fonts: ^6.1.0
  dio: ^5.4.0
  get_it: ^7.6.4
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_screenutil: ^5.9.0
  flutter_form_builder: ^9.2.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  permission_handler: ^11.3.1
  form_builder_validators: ^9.1.0
  easy_refresh: ^3.3.4
  timeago: ^3.6.0
  extended_masked_text: ^2.3.1
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  table_calendar: ^3.1.2
  dropdown_button2: ^2.3.9
  flutter_rating_bar: ^4.0.1
  flutter_animate: ^4.5.0
  skeletonizer: ^1.0.1
  icons_launcher: ^2.1.7
  url_launcher: ^6.2.4
  auto_size_text_field: ^2.2.2
  flutter_intro: ^3.2.0
  animated_bottom_navigation_bar: ^1.3.3
  geolocator: ^12.0.0
  pedometer: ^4.0.2
  rxdart: ^0.28.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  fpdart: ^1.1.0
  flutter_local_notifications: ^17.2.3
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  firebase_storage: ^12.2.0
  alarm: ^3.1.5
  camera: ^0.10.5+5
  fl_chart: ^0.69.0
  dart_jsonwebtoken: ^2.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  go_router_builder: ^2.4.0
  json_serializable: ^6.7.1
  flutter_gen: ^5.3.2

dependency_overrides:
  intl: 0.19.0  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    # - assets/improve_shape.png
    - assets/audio_count_down.mp3
    - assets/audio_nature_sounds.mp3
    - assets/audio_goggin_dont_care.mp3
    - assets/audio_hurry_up.mp3
    - assets/audio_its_time_fo_scoo.mp3
    - assets/audio_just_do_it.mp3
    - assets/audio_riot.mp3
    # - images/a_dot_ham.jpeg

# flutter pub global run intl_utils:generate
flutter_intl:
  enabled: true
  arb-dir: lib/l10n
  template-arb-file: lib/intl_en.arb
  output-localization-file: .dart_tool/app_localizations.dart

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/img_splash.png

# dart run icons_launcher:create
icons_launcher:
  image_path: "assets/img_splash.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
